Sprint 05
NutsCraker/MovieQuiz-ios pull request #2
Opened 2022-12-06 09:45 UTC by NutsCraker

Постарался все исправить, вроде многое получилось

2022-12-06 19:31 UTC, ABashkirova requested changes
Давай доделаем старт новой игры из замыкания. Я примерно накидала как это должно быть, попробуй сделать самостоятельно дальше, либо обратись за помощью к Наставнику.

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Models/AlertModel.swift
> +   // let completion: (()->Void)
Давай расскоментируем и используем это в презентере

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/ AlertPresenter.swift
> +    }
> Обработка нажатия на кнопку алерт реализована с использованием либо замыкания, либо делегата.

В AlertModel складываем в completion блок кода, который хотим выполнить по нажатию на кнопку. И создаем UIAlertAction с третьим параметром - замыканием, где этот блок кода вызываем: 
```suggestion
    func show(result : AlertModel) {
        let alert = UIAlertController(title: result.title, message: result.message, preferredStyle: .alert)
        let action = UIAlertAction(title: result.buttonText, style: .default) { 
            result.completion()
        }
        alert.addAction(action)
        
        viewController?.present(alert, animated: true, completion: nil)// просила переименовать в контроллер
    }
```

лишнее удалила, как просила в предыдущем ревью

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/ AlertPresenter.swift
> +    private var questionFactory: QuestionFactoryProtocol? = nil
```suggestion
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    func didReceiveNextQuestion(question: QuizQuestion?) {
функции хорошо бы перечислять после свойств класса

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    {
Фигурная скобка убежала 
```suggestion
    
    override func viewDidLoad() {
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }}
Форматирование должно выглядеть так:
```suggestion
        }
    }
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    {
Кажется я неточно выразилась, открывающая должна оставаться на той же строке:
```suggestion
    private func showNextQuestionOrResults() {
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            UIView.animate(withDuration: 0, delay: 0.5, options: [], animations: { })
эта строчка ничего не делает

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                                       buttonText: "Сыграть ещё раз")
```suggestion
                                       buttonText: "Сыграть ещё раз",
                                       completion: { [weak self] in  //<-- вот так передается язамыкание
                                          self?.currentQuestionIndex = 0
                                          self?.correctAnswers = 0
                                          self?.questionFactory?.requestNextQuestion()
                                       }
                                   )
                               
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        {
Везде надо вернуть как было
```suggestion
        if currentQuestionIndex == questionsAmount - 1 {
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            }
```suggestion
            else {
                return
            }
```

2022-12-06 19:31 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +        gamesCount = gamesCount + 1
отлично!

2022-12-06 19:32 UTC, ABashkirova commented
Обрати внимание, что текст вопроса перестал влезать полностью:
<img width="550" alt="Снимок экрана 2022-12-06 в 21 18 51" src="https://user-images.githubusercontent.com/20269264/206005003-fe886a70-67a6-41af-a881-9d761ad04e54.png">

2022-12-06 19:45 UTC, NutsCraker commented
> Обрати внимание, что текст вопроса перестал влезать полностью: <img alt="Снимок экрана 2022-12-06 в 21 18 51" width="550" src="https://user-images.githubusercontent.com/20269264/206005003-fe886a70-67a6-41af-a881-9d761ad04e54.png">

Очень странно, у меня тоже симулятор на Iphone 14  и все помещается

<img width="531" alt="image" src="https://user-images.githubusercontent.com/117199645/206007732-648e3b45-96e1-4832-b60e-325b972ddfd0.png">

2022-12-07 08:06 UTC, ABashkirova commented
14 Pro и 14 разные айфоны

2022-12-07 08:07 UTC, ABashkirova commented
Решение к сожалению лишь компромиссное: надо изменить величины констрейнтов внутри контейнера вопроса, чтобы пространства было чуть больше

2022-12-07 08:59 UTC, NutsCraker commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                                       buttonText: "Сыграть ещё раз")
Такой вариант я тоже пробовал, но вопрос в фоне меняется сразу после того как был показан Алерт, а не после нажатия кнопки на Алерте... 
Видимо у меня проблемы с пониманием работы алерта и куда добавлять этот complition

<img width="889" alt="image" src="https://user-images.githubusercontent.com/117199645/206134359-4749bf25-107d-409b-a79e-4c98536f690d.png">

2022-12-07 09:11 UTC, NutsCraker commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                                       buttonText: "Сыграть ещё раз")
Не заработало, пока не добавил "_" , и это как то было не совсем очевидно...
<img width="711" alt="image" src="https://user-images.githubusercontent.com/117199645/206136931-ab8d7cfd-3003-4b06-bd24-f558a9c65533.png">

2022-12-07 09:20 UTC, NutsCraker commented on MovieQuiz/Presentation/ AlertPresenter.swift
> +    }
Я в итоге запихал его в handler UIAlertAction

`let action = UIAlertAction(title: result.buttonText, style: .default, handler: result.completion)`

Почему стилисчически правильно именно переименовать? Не совсем понятно - так же название больше говорит за себя?

2022-12-07 09:41 UTC, NutsCraker commented
> 

Получается, что тогда мы отклоняемся от макета.... ?

2022-12-07 09:48 UTC, closed without merging

2022-12-07 09:49 UTC, NutsCraker commented
Так, попробую создать новый pull request

2022-12-07 11:23 UTC, ABashkirova commented
> Получается, что тогда мы отклоняемся от макета.... ?

С текстами, особенно динамическими, часто приходится немного отступать от макета. В этом и сложность верстки: дизайнер не всегда достаточно хорошо передает как это должно работать для разных экранов. Тут софтскилы разработчика: знать что такое может случиться, прийти к дизайнеру и предложить варианты как ты это можешь решить. но у нас нет в доступе дизайнера, поэтому сами обходимся) Жизнь разработчика – она такая :)